"""add_user_leader_department_fields

Revision ID: 050821918a70
Revises: 518365f4d0b1
Create Date: 2026-05-22 23:33:16.137651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '050821918a70'
down_revision: Union[str, None] = '518365f4d0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailyreport', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.alter_column('dailyreport', 'files_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('meetingnote', 'ai_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('meetingnote', 'files_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('meetingnote', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('project', 'files_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_dept_role'), 'rbac_department_role', type_='unique')
    op.drop_constraint(op.f('rbac_permission_code_key'), 'rbac_permission', type_='unique')
    op.drop_constraint(op.f('rbac_role_code_key'), 'rbac_role', type_='unique')
    op.drop_constraint(op.f('uq_role_perm'), 'rbac_role_permission', type_='unique')
    op.drop_constraint(op.f('uq_user_role'), 'rbac_user_role', type_='unique')
    op.add_column('user', sa.Column('leader_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['leader_id'], ['id'])
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    op.add_column('weeklysummary', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.alter_column('wiki_page', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('wiki_page_version', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wiki_page_version', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('wiki_page', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('weeklysummary', 'status')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'job_title')
    op.drop_column('user', 'department_id')
    op.drop_column('user', 'leader_id')
    op.create_unique_constraint(op.f('uq_user_role'), 'rbac_user_role', ['user_id', 'role_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_role_perm'), 'rbac_role_permission', ['role_id', 'permission_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('rbac_role_code_key'), 'rbac_role', ['code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('rbac_permission_code_key'), 'rbac_permission', ['code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_dept_role'), 'rbac_department_role', ['department_id', 'role_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('project', 'files_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('meetingnote', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('meetingnote', 'files_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('meetingnote', 'ai_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dailyreport', 'files_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('dailyreport', 'status')
    # ### end Alembic commands ###
