"""baseline_postgresql

Revision ID: ba5411e0317b
Revises: 
Create Date: 2026-05-03 21:59:47.055058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba5411e0317b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiprompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('user_prompt_template', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aiprompt_task_type'), 'aiprompt', ['task_type'], unique=True)
    op.create_table('fieldoption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelprovider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('models', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supported_models_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduledtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_config', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_params', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('chatconversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatconversation_user_id'), 'chatconversation', ['user_id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('core_products', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recent_news', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_user_id'), 'customer', ['user_id'], unique=False)
    op.create_table('dailyreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('content_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providermodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['modelprovider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providermodel_provider_id'), 'providermodel', ['provider_id'], unique=False)
    op.create_table('systempreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systempreference_key'), 'systempreference', ['key'], unique=False)
    op.create_index(op.f('ix_systempreference_user_id'), 'systempreference', ['user_id'], unique=False)
    op.create_table('taskmodelconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['modelprovider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type')
    )
    op.create_table('weeklysummary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('summary_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weeklysummary_user_id'), 'weeklysummary', ['user_id'], unique=False)
    op.create_index(op.f('ix_weeklysummary_week_start'), 'weeklysummary', ['week_start'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatconversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_conversation_id'), 'chatmessage', ['conversation_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_scenario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sales_person', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cloud_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_user_id'), 'project', ['user_id'], unique=False)
    op.create_table('meetingnote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attendees', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetingnote_user_id'), 'meetingnote', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetingnote_user_id'), table_name='meetingnote')
    op.drop_table('meetingnote')
    op.drop_index(op.f('ix_project_user_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_chatmessage_conversation_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_weeklysummary_week_start'), table_name='weeklysummary')
    op.drop_index(op.f('ix_weeklysummary_user_id'), table_name='weeklysummary')
    op.drop_table('weeklysummary')
    op.drop_table('taskmodelconfig')
    op.drop_index(op.f('ix_systempreference_user_id'), table_name='systempreference')
    op.drop_index(op.f('ix_systempreference_key'), table_name='systempreference')
    op.drop_table('systempreference')
    op.drop_index(op.f('ix_providermodel_provider_id'), table_name='providermodel')
    op.drop_table('providermodel')
    op.drop_table('dailyreport')
    op.drop_index(op.f('ix_customer_user_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_chatconversation_user_id'), table_name='chatconversation')
    op.drop_table('chatconversation')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('scheduledtask')
    op.drop_table('modelprovider')
    op.drop_table('logentry')
    op.drop_table('fieldoption')
    op.drop_index(op.f('ix_aiprompt_task_type'), table_name='aiprompt')
    op.drop_table('aiprompt')
    # ### end Alembic commands ###
