"""add_files_json_to_reports_meetings_projects

Revision ID: f8c93d152e1c
Revises: 51369b4e0974
Create Date: 2026-05-05 01:58:33.447057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f8c93d152e1c'
down_revision: Union[str, None] = '51369b4e0974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailyreport', sa.Column('files_json', sa.Text(), nullable=True))
    op.add_column('meetingnote', sa.Column('files_json', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('files_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'files_json')
    op.drop_column('meetingnote', 'files_json')
    op.drop_column('dailyreport', 'files_json')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
